// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbveIk2b5j8ZEUByldTFFOmW58_XrIkt4',
    appId: '1:989688927883:web:1f6c1fccc9740ddd55e68e',
    messagingSenderId: '989688927883',
    projectId: 'parentcontrol-9a079',
    authDomain: 'parentcontrol-9a079.firebaseapp.com',
    storageBucket: 'parentcontrol-9a079.firebasestorage.app',
    measurementId: 'G-LG8GC4CC82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0kAQLy3d1GRIG3Ie66BtSf25zu_nfKmQ',
    appId: '1:989688927883:android:81a5d2f41dbda87b55e68e',
    messagingSenderId: '989688927883',
    projectId: 'parentcontrol-9a079',
    storageBucket: 'parentcontrol-9a079.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_9nxKYDcbnuxDOHO7PsU8tmHouy5Ys88',
    appId: '1:989688927883:ios:76ffb4b0ca8339c055e68e',
    messagingSenderId: '989688927883',
    projectId: 'parentcontrol-9a079',
    storageBucket: 'parentcontrol-9a079.firebasestorage.app',
    iosBundleId: 'com.example.parentalradar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_9nxKYDcbnuxDOHO7PsU8tmHouy5Ys88',
    appId: '1:989688927883:ios:76ffb4b0ca8339c055e68e',
    messagingSenderId: '989688927883',
    projectId: 'parentcontrol-9a079',
    storageBucket: 'parentcontrol-9a079.firebasestorage.app',
    iosBundleId: 'com.example.parentalradar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbveIk2b5j8ZEUByldTFFOmW58_XrIkt4',
    appId: '1:989688927883:web:9ed7ba6480100e1b55e68e',
    messagingSenderId: '989688927883',
    projectId: 'parentcontrol-9a079',
    authDomain: 'parentcontrol-9a079.firebaseapp.com',
    storageBucket: 'parentcontrol-9a079.firebasestorage.app',
    measurementId: 'G-KJPM44QFBY',
  );
}
